apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-python-time.fullname" . }}
  labels:
    {{- include "demo-python-time.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-python-time.selectorLabels" . | nindent 4 }}
